spring.application.name=odin
##spring.datasource.url=jdbc:mysql://localhost:8889/odin
##spring.datasource.username=root
##spring.datasource.password=root
##spring.jpa.hibernate.ddl-auto=update

## --- CONEXI�N MYSQL (MySQLDialect) ---

#spring.datasource.url=jdbc:mysql://srv1570.hstgr.io:3306/u713174096_odin
#spring.datasource.username =u713174096_odin
#spring.datasource.password=@Odin523142
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

## --- CONEXI�N SUPABASE (PostgreSQL) ---
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.qafgkqsqzinxenyosmln
spring.datasource.password=G3st0rD0cD1n
spring.datasource.driver-class-name=org.postgresql.Driver

## --- CONFIGURACI�N DE HIBERNATE / JPA ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
##spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

## --- ARCHIVOS ADJUNTOS (uploads) ---
app.upload-dir=uploads
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB